### ISSUE TITLE
When I click start import nothing happens.

### ISSUE THREAD

**Issue by aweocelot** [ptrumpis/snap-lens-cache-import#1]
Everything is working apart from the import. Docker, the snap server v3, snap camera, but I've tried to import the lens and settings.json using the web interface and nothing changes on the server or in snap camera. I haven't used docker before. Is there an easy way to manually import files?

Thank you.

**Comment by ptrumpis** [comment]
Is this url callable in your browser?
https://studio-app.snapchat.com/vc/v1/import/cache

You should see the message
```
"import enabled"
```

**Comment by aweocelot** [comment]
No, getting an error.

> This site can’t be reached

**Comment by ptrumpis** [comment]
The docker server needs to be running.
If the server is running and the site is still not reachable you will have to check your /etc/hosts file
