### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by elliereaux** [ptrumpis/snap-lens-cache-import#2]
OMG finally got the server working (thank you oh god of all thing SC..and for putting up with me). Now how do i import my lenses on mac>?

**Comment by ptrumpis** [comment]
https://ptrumpis.github.io/snap-lens-cache-import/

cached lenses and settings.json should be in a sub folder of `/Users/{YOUR_USER_NAME}/Library/Preferences/Snap/Snap Camera/`

Drag&Drop your files on to the area and click upload
